- name: Ensure that JVM is installed
  yum: name=java-1.7.0-openjdk-devel state=present
  sudo: yes

- name: Install datastax repo
  copy:
    src=datastax.repo
    dest=/etc/yum.repos.d/datastax.repo
    owner=root group=root mode=0644
  sudo: yes

- name: Install opscenter
  yum: name=opscenter-free state=present
  sudo: yes

- name: Register iptable rules
  shell: iptables -L
  register: iptablesrules
  sudo: yes

- name: Allow Opscenter web
  command: /sbin/iptables -I INPUT 1 -p tcp --dport 8888 -j ACCEPT -m comment --comment "OpsCenter"
  sudo: yes
  when: iptablesrules.stdout.find("OpsCenter") == -1

- name: Allow Opscenter listener
  command: /sbin/iptables -I INPUT 1 -p tcp --dport 61620 -j ACCEPT -m comment --comment "OpscenterListener"
  sudo: yes
  when: iptablesrules.stdout.find("OpscenterListener") == -1

- name: save iptables
  shell: iptables-save > /etc/sysconfig/iptables
  sudo: yes

- name: Start opscenter
  service: name=opscenterd state=started
  sudo: yes
