- name: Ensure that JVM is installed
  yum: name=java-1.7.0-openjdk-devel state=present
  sudo: yes

- name: Install datastax repo
  copy:
    src=datastax.repo
    dest=/etc/yum.repos.d/datastax.repo
    owner=root group=root mode=0644
  sudo: yes

- name: Install jna
  yum: name=jna state=present
  sudo: yes

- name: Install cassandra
  yum: name=dsc20 state=present
  sudo: yes

- name: Register iptable rules
  shell: iptables -L
  register: iptablesrules
  sudo: yes
  tags: iptables

- name: Allow cassandra rpc port through firewall
  command: /sbin/iptables -I INPUT 1 -p tcp --dport 9160 -j ACCEPT -m comment --comment "CassandraRpc"
  sudo: yes
  when: iptablesrules.stdout.find("CassandraRpc") == -1
  tags: iptables

- name: Allow Cassandra inter-node cluster communication
  command: /sbin/iptables -I INPUT 1 -p tcp --dport 7000 -j ACCEPT -m comment --comment "CassandraInterNode"
  sudo: yes
  when: iptablesrules.stdout.find("CassandraInterNode") == -1
  tags: iptables

- name: Allow Cassandra JMX monitoring
  command: /sbin/iptables -I INPUT 1 -p tcp --dport 7199 -j ACCEPT -m comment --comment "CassandraJMX"
  sudo: yes
  when: iptablesrules.stdout.find("CassandraJMX") == -1
  tags: iptables

- name: Allow Cassandra cql native transport
  command: /sbin/iptables -I INPUT 1 -p tcp --dport 9042 -j ACCEPT -m comment --comment "CassandraNative"
  sudo: yes
  when: iptablesrules.stdout.find("CassandraNative") == -1
  tags: iptables

- name: Allow Opscenter monitoring
  command: /sbin/iptables -I INPUT 1 -p tcp --dport 61620 -j ACCEPT -m comment --comment "OpscenterMonitoring"
  sudo: yes
  when: iptablesrules.stdout.find("CassandraNative") == -1
  tags: iptables


- name: Allow Opscenter agents
  command: /sbin/iptables -I INPUT 1 -p tcp --dport 61621 -j ACCEPT -m comment --comment "OpscenterAgents"
  sudo: yes
  when: iptablesrules.stdout.find("CassandraNative") == -1
  tags: iptables

- name: save iptables
  shell: iptables-save > /etc/sysconfig/iptables
  sudo: yes
  tags: iptables

- name: stop cassandra
  service: name=cassandra state=stopped
  sudo: yes

- name: delete system data
  command: rm -rf /var/lib/cassandra/data/system/*
  sudo: yes

- name: copy config
  template: src=cassandra.yaml dest=/etc/cassandra/conf/
  sudo: yes

- name: set hostname/ip for JMX
  lineinfile: dest=/etc/cassandra/conf/cassandra-env.sh regexp='hostname' line='JVM_OPTS="$JVM_OPTS -Djava.rmi.server.hostname={{ inventory_hostname }}"' backup=yes
  sudo: yes

- name: ensure tmp is not mounted as noexec
  command: mount -o remount,exec /dev/mapper/vg-tmp
  sudo: yes

- name: start cassandra
  service: name=cassandra state=started
  sudo: yes

- name: install lsof, htop, iftop
  yum: name={{ item }} state=present
  with_items:
    - lsof
    - htop
    - iftop
  sudo: yes

#  set /etc/security/limits.d/90-nproc.conf -> * - nproc 32768
#  sudo sysctl -p
#  sudo swapoff --all